10.11.19   15:54:46 - __main__ - ERROR - ERROR on group page
Traceback (most recent call last):
  File "C:/Users/ART/instagram_bot/test/insta_test.py", line 57, in get_list_of_followers_links
    last_of_followers = list_of_followers[-1]
IndexError: list index out of range
